import { ApolloClient, gql, InMemoryCache, ApolloProvider } from '@apollo/client'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import StudentTable from '../Components/StudentTable/StudentTable'
import styles from '../styles/Home.module.css'

const client = new ApolloClient({
  uri: "http://localhost:4000/graphql",
  cache: new InMemoryCache()
})

export const getServerSideProps = async() => {
  // const client = new ApolloClient({
  //   uri: "http://localhost:4000/graphql",
  //   cache: new InMemoryCache()
  // })
  const { data } = await client.query({
    query: gql`
    query{
       getAll 
       {
         id
         Name
         Email
         Phone
         Dob
         Subjects
       }
     }
    `
  })
  console.log('data', data );
  return {
    props: { data : data.getAll }
  }
}

export default function Home({ data } ) {
  
  const initialState = data;
  const [info, setInfo] = useState(initialState)
  console.log('info', info );

  return (
    <>
    <div className={styles.gain}>
    <h1> Gain Solutions Interview Task </h1>
    </div>
    <div  className={styles.container} >
      <Head>
        <title> Gain Solutions LTD </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ApolloProvider client={ client } >
        <StudentTable info={info}  />
      </ApolloProvider>

      
    </div>
    </>
  )
}
